/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/album': RouteRecordInfo<
      '/album',
      '/album',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/girls/': RouteRecordInfo<
      '/girls/',
      '/girls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/message/': RouteRecordInfo<
      '/message/',
      '/message',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/alist_html_body': RouteRecordInfo<
      '/posts/alist_html_body',
      '/posts/alist_html_body',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/alist_html_head': RouteRecordInfo<
      '/posts/alist_html_head',
      '/posts/alist_html_head',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/captive_portal_detection': RouteRecordInfo<
      '/posts/captive_portal_detection',
      '/posts/captive_portal_detection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/check_unused_rule_providers': RouteRecordInfo<
      '/posts/check_unused_rule_providers',
      '/posts/check_unused_rule_providers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cloudflare_add_delete_domain': RouteRecordInfo<
      '/posts/cloudflare_add_delete_domain',
      '/posts/cloudflare_add_delete_domain',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/delete_github_release': RouteRecordInfo<
      '/posts/delete_github_release',
      '/posts/delete_github_release',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/domain_check_loop': RouteRecordInfo<
      '/posts/domain_check_loop',
      '/posts/domain_check_loop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/domain_ssl_script': RouteRecordInfo<
      '/posts/domain_ssl_script',
      '/posts/domain_ssl_script',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/extract_ip_port': RouteRecordInfo<
      '/posts/extract_ip_port',
      '/posts/extract_ip_port',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/fonts_linux_install': RouteRecordInfo<
      '/posts/fonts_linux_install',
      '/posts/fonts_linux_install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/github_release_auto_upload': RouteRecordInfo<
      '/posts/github_release_auto_upload',
      '/posts/github_release_auto_upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hysteria2_script': RouteRecordInfo<
      '/posts/hysteria2_script',
      '/posts/hysteria2_script',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ked_neno_commands': RouteRecordInfo<
      '/posts/ked_neno_commands',
      '/posts/ked_neno_commands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mihomo_dns_webrtc': RouteRecordInfo<
      '/posts/mihomo_dns_webrtc',
      '/posts/mihomo_dns_webrtc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mihomo_linux_install': RouteRecordInfo<
      '/posts/mihomo_linux_install',
      '/posts/mihomo_linux_install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/nginx_disguise': RouteRecordInfo<
      '/posts/nginx_disguise',
      '/posts/nginx_disguise',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/proxy_linux': RouteRecordInfo<
      '/posts/proxy_linux',
      '/posts/proxy_linux',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/sfm_automation_guide': RouteRecordInfo<
      '/posts/sfm_automation_guide',
      '/posts/sfm_automation_guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/webp_convert_to': RouteRecordInfo<
      '/posts/webp_convert_to',
      '/posts/webp_convert_to',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Your_Lie_in_April': RouteRecordInfo<
      '/posts/Your_Lie_in_April',
      '/posts/Your_Lie_in_April',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/privacy/': RouteRecordInfo<
      '/privacy/',
      '/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.7_mag_9505467db5c1e7abfeb09819c694bd7e/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.7_@babel+parser_960bebb14b7ec01077ff4b56c17bd8df/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/album.md': {
      routes:
        | '/album'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/girls/index.md': {
      routes:
        | '/girls/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'pages/message/index.md': {
      routes:
        | '/message/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.7_mag_9505467db5c1e7abfeb09819c694bd7e/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.7_mag_9505467db5c1e7abfeb09819c694bd7e/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/alist_html_body.md': {
      routes:
        | '/posts/alist_html_body'
      views:
        | never
    }
    'pages/posts/alist_html_head.md': {
      routes:
        | '/posts/alist_html_head'
      views:
        | never
    }
    'pages/posts/captive_portal_detection.md': {
      routes:
        | '/posts/captive_portal_detection'
      views:
        | never
    }
    'pages/posts/check_unused_rule_providers.md': {
      routes:
        | '/posts/check_unused_rule_providers'
      views:
        | never
    }
    'pages/posts/cloudflare_add_delete_domain.md': {
      routes:
        | '/posts/cloudflare_add_delete_domain'
      views:
        | never
    }
    'pages/posts/delete_github_release.md': {
      routes:
        | '/posts/delete_github_release'
      views:
        | never
    }
    'pages/posts/domain_check_loop.md': {
      routes:
        | '/posts/domain_check_loop'
      views:
        | never
    }
    'pages/posts/domain_ssl_script.md': {
      routes:
        | '/posts/domain_ssl_script'
      views:
        | never
    }
    'pages/posts/extract_ip_port.md': {
      routes:
        | '/posts/extract_ip_port'
      views:
        | never
    }
    'pages/posts/fonts_linux_install.md': {
      routes:
        | '/posts/fonts_linux_install'
      views:
        | never
    }
    'pages/posts/github_release_auto_upload.md': {
      routes:
        | '/posts/github_release_auto_upload'
      views:
        | never
    }
    'pages/posts/hysteria2_script.md': {
      routes:
        | '/posts/hysteria2_script'
      views:
        | never
    }
    'pages/posts/ked_neno_commands.md': {
      routes:
        | '/posts/ked_neno_commands'
      views:
        | never
    }
    'pages/posts/mihomo_dns_webrtc.md': {
      routes:
        | '/posts/mihomo_dns_webrtc'
      views:
        | never
    }
    'pages/posts/mihomo_linux_install.md': {
      routes:
        | '/posts/mihomo_linux_install'
      views:
        | never
    }
    'pages/posts/nginx_disguise.md': {
      routes:
        | '/posts/nginx_disguise'
      views:
        | never
    }
    'pages/posts/proxy_linux.md': {
      routes:
        | '/posts/proxy_linux'
      views:
        | never
    }
    'pages/posts/sfm_automation_guide.md': {
      routes:
        | '/posts/sfm_automation_guide'
      views:
        | never
    }
    'pages/posts/webp_convert_to.md': {
      routes:
        | '/posts/webp_convert_to'
      views:
        | never
    }
    'pages/posts/Your_Lie_in_April.md': {
      routes:
        | '/posts/Your_Lie_in_April'
      views:
        | never
    }
    'pages/privacy/index.md': {
      routes:
        | '/privacy/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
