/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/album': RouteRecordInfo<'/album', '/album', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/message/': RouteRecordInfo<'/message/', '/message', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/alist_html_body': RouteRecordInfo<'/posts/alist_html_body', '/posts/alist_html_body', Record<never, never>, Record<never, never>>,
    '/posts/alist_html_head': RouteRecordInfo<'/posts/alist_html_head', '/posts/alist_html_head', Record<never, never>, Record<never, never>>,
    '/posts/check_unused_rule_providers': RouteRecordInfo<'/posts/check_unused_rule_providers', '/posts/check_unused_rule_providers', Record<never, never>, Record<never, never>>,
    '/posts/cloudflare_add_delete_domain': RouteRecordInfo<'/posts/cloudflare_add_delete_domain', '/posts/cloudflare_add_delete_domain', Record<never, never>, Record<never, never>>,
    '/posts/delete_github_release': RouteRecordInfo<'/posts/delete_github_release', '/posts/delete_github_release', Record<never, never>, Record<never, never>>,
    '/posts/domain_check_loop': RouteRecordInfo<'/posts/domain_check_loop', '/posts/domain_check_loop', Record<never, never>, Record<never, never>>,
    '/posts/domain_ssl_script': RouteRecordInfo<'/posts/domain_ssl_script', '/posts/domain_ssl_script', Record<never, never>, Record<never, never>>,
    '/posts/extract_ip_port': RouteRecordInfo<'/posts/extract_ip_port', '/posts/extract_ip_port', Record<never, never>, Record<never, never>>,
    '/posts/fonts_linux_install': RouteRecordInfo<'/posts/fonts_linux_install', '/posts/fonts_linux_install', Record<never, never>, Record<never, never>>,
    '/posts/github_release_auto_upload': RouteRecordInfo<'/posts/github_release_auto_upload', '/posts/github_release_auto_upload', Record<never, never>, Record<never, never>>,
    '/posts/hysteria2_script': RouteRecordInfo<'/posts/hysteria2_script', '/posts/hysteria2_script', Record<never, never>, Record<never, never>>,
    '/posts/ked_neno_commands': RouteRecordInfo<'/posts/ked_neno_commands', '/posts/ked_neno_commands', Record<never, never>, Record<never, never>>,
    '/posts/mihomo_dns_webrtc': RouteRecordInfo<'/posts/mihomo_dns_webrtc', '/posts/mihomo_dns_webrtc', Record<never, never>, Record<never, never>>,
    '/posts/mihomo_linux_install': RouteRecordInfo<'/posts/mihomo_linux_install', '/posts/mihomo_linux_install', Record<never, never>, Record<never, never>>,
    '/posts/nginx_disguise': RouteRecordInfo<'/posts/nginx_disguise', '/posts/nginx_disguise', Record<never, never>, Record<never, never>>,
    '/posts/proxy_linux': RouteRecordInfo<'/posts/proxy_linux', '/posts/proxy_linux', Record<never, never>, Record<never, never>>,
    '/posts/sfm_automation_guide': RouteRecordInfo<'/posts/sfm_automation_guide', '/posts/sfm_automation_guide', Record<never, never>, Record<never, never>>,
    '/posts/webp_convert_to': RouteRecordInfo<'/posts/webp_convert_to', '/posts/webp_convert_to', Record<never, never>, Record<never, never>>,
    '/posts/Your_Lie_in_April': RouteRecordInfo<'/posts/Your_Lie_in_April', '/posts/Your_Lie_in_April', Record<never, never>, Record<never, never>>,
    '/privacy/': RouteRecordInfo<'/privacy/', '/privacy', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
