name: GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Checkout the other repository
        uses: actions/checkout@v3
        with:
          repository: Kwisma/cf-worker-mihomo  # 替换为目标仓库的所有者和名称
          ref: main  # 目标仓库的分支
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GitHub token
          path: cf-worker-mihomo@main

      - name: Checkout the other repository
        uses: actions/checkout@v3
        with:
          repository: peiyingyao/Rule-for-OCD  # 替换为目标仓库的所有者和名称
          ref: master  # 目标仓库的分支
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GitHub token
          path: Rule-for-OCD@master

      - name: Checkout the other repository
        uses: actions/checkout@v3
        with:
          repository: qljsyph/ruleset-icon  # 替换为目标仓库的所有者和名称
          ref: main  # 目标仓库的分支
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GitHub token
          path: ruleset-icon@main

      - name: Checkout the other repository
        uses: actions/checkout@v3
        with:
          repository: DustinWin/ruleset_geodata  # 替换为目标仓库的所有者和名称
          ref: mihomo-ruleset  # 目标仓库的分支
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认的 GitHub token
          path: ruleset_geodata@mihomo-ruleset

      - name: Copy directory from the other repository
        run: |
          mkdir -p public/gh/Kwisma/cf-worker-mihomo@main
          mkdir -p public/gh/peiyingyao/Rule-for-OCD@master
          mkdir -p public/gh/qljsyph/ruleset-icon@main
          mkdir -p public/gh/DustinWin/ruleset_geodata@mihomo-ruleset
          cp -r cf-worker-mihomo@main/* public/gh/Kwisma/cf-worker-mihomo@main
          cp -r Rule-for-OCD@master/* public/gh/peiyingyao/Rule-for-OCD@master
          cp -r ruleset-icon@main/* public/gh/qljsyph/ruleset-icon@main
          cp -r ruleset_geodata@mihomo-ruleset/* public/gh/DustinWin/ruleset_geodata@mihomo-ruleset

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🌌 Build Valaxy Blog
        run: npm run build

      - name: 📦 install wrangler
        run: npm install -g wrangler

      - name: 🚀 Deploy to Cloudflare Pages
        run: npx wrangler deploy --name blog --compatibility-date 2025-01-08 --assets=./dist
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
