name: deploy website

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新环境
    steps:
      - uses: actions/checkout@v2  # Checkout 仓库代码

      # 可选: 如果需要构建命令，例如 Angular 项目
      - run: |
          npm install  # 安装依赖
          npm run build

      - uses: amondnet/vercel-action@v25  # 使用 Vercel 部署
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # 传入 Vercel token
          github-token: ${{ secrets.GITHUB_TOKEN }}  # 可选: 传入 GitHub token
          vercel-args: '--main'  # 部署到生产环境
          vercel-org-id: ${{ secrets.ORG_ID }}  # Vercel 组织 ID
          vercel-project-id: ${{ secrets.PROJECT_ID }}  # Vercel 项目 ID
          working-directory: ./sub-directory  # 如果代码在子目录下
